# Generated by Django 3.0.1 on 2022-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221102_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('ORTHOMOSAIC', 'Orthomosaic'), ('SHAPEFILE', 'Shapefile'), ('INDEX', 'Index'), ('RGB', 'Rgb')], max_length=20),
        ),
    ]
