# Generated by Django 3.0.1 on 2022-12-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221229_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('MULTIESPECTRAL', 'Multiespectral'), ('SHAPEFILE', 'Shapefile'), ('INDEX', 'Index'), ('RGB', 'Rgb'), ('KML', 'Kml')], max_length=20),
        ),
    ]
