# Generated by Django 3.0.1 on 2022-12-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221229_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='camera',
            field=models.CharField(choices=[('REDEDGE', 'Micasense RedEdge-M'), ('PARROT', 'Parrot Sequoia')], max_length=20),
        ),
    ]
