# Generated by Django 3.0.1 on 2022-12-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221230_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='camera',
            field=models.CharField(choices=[('REDEDGE', 'Micasense RedEdge-M'), ('PARROT', 'Parrot Sequoia'), ('VECTOR', 'Vector')], max_length=20),
        ),
    ]
