# Generated by Django 3.0.1 on 2023-01-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221230_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='project',
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.UserProject')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.Layer'),
        ),
    ]
