# Generated by Django 3.0.1 on 2023-01-04 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230104_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
