# Generated by Django 3.0.1 on 2023-01-17 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230105_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('VECTOR', 'VECTOR')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
