# Generated by Django 3.0.1 on 2023-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='camera',
            field=models.CharField(choices=[('REDEDGE', 'Micasense RedEdge-M'), ('PARROT', 'Parrot Sequoia'), ('VECTOR', 'Vector'), ('RGB', 'RGB'), ('NONE', 'none')], max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('MULTIESPECTRAL', 'Multiespectral'), ('SHAPEFILE', 'Shapefile'), ('INDEX', 'Index'), ('MODEL', 'Model'), ('RGB', 'RGB'), ('KML', 'Kml')], max_length=20),
        ),
    ]
