# Generated by Django 3.0.1 on 2023-02-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230212_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='source',
        ),
    ]
