# Generated by Django 3.0.1 on 2023-02-12 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_artifact_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
