# Generated by Django 3.0.1 on 2023-03-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_artifact_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
