# Generated by Django 3.0.1 on 2023-03-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userproject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
