# Generated by Django 3.0.1 on 2023-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userproject_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='wallpaper',
            field=models.CharField(max_length=500),
        ),
    ]
