# Generated by Django 3.0.1 on 2023-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230315_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
