# Generated by Django 3.0.1 on 2023-03-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230315_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='date',
        ),
    ]
