# Generated by Django 3.0.1 on 2023-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_userproject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='wallpaper',
            field=models.CharField(default='agrins/card_proj.png', max_length=500),
        ),
    ]
