# Generated by Django 3.0.1 on 2022-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210404_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='flights',
            field=models.ManyToManyField(default=None, related_name='user_projects', to='core.Flight'),
        ),
    ]
