# Generated by Django 3.0.1 on 2022-10-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20221023_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='flights',
            field=models.ManyToManyField(default=None, null=True, related_name='user_projects', to='core.Flight'),
        ),
    ]
