# Generated by Django 3.0.1 on 2023-03-17 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230315_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproject',
            name='wallpaper',
            field=models.CharField(default='agrins/card_proj.png', max_length=300),
        ),
    ]
