# Generated by Django 3.0.1 on 2022-10-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20221023_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='flights',
        ),
    ]
