# Generated by Django 3.0.1 on 2023-03-27 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
