# Generated by Django 3.0.1 on 2022-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20221024_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DEMO_USER', 'DemoUser'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('ADMIN', 'Admin')], default='ACTIVE', max_length=20),
        ),
    ]
