# Generated by Django 3.0.1 on 2023-03-27 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meta',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
