# Generated by Django 3.0.1 on 2022-10-27 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20221025_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='flights',
            field=models.ManyToManyField(related_name='user_projects', to='core.Flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='annotations',
            field=models.TextField(default='Anotations'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='camera',
            field=models.CharField(choices=[('REDEDGE', 'Micasense RedEdge'), ('RGB', 'RGB')], default='RGB', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(default='Flight-provider', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for images'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='COMPLETE', max_length=10),
        ),
    ]
