# Generated by Django 3.0.1 on 2022-10-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20221027_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='num_images',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
