# Generated by Django 3.0.1 on 2023-04-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230328_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maximum_space',
            field=models.PositiveIntegerField(choices=[('DEMO_USER', 'DemoUser'), ('ACTIVE', 'Active'), ('ADVANCED', 'Advanced'), ('DELETED', 'Deleted'), ('ADMIN', 'Admin')], default='ACTIVE'),
        ),
    ]
