# Generated by Django 3.0.1 on 2023-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20230403_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maximum_space',
            field=models.PositiveIntegerField(default=10485760),
        ),
    ]
